_schema: _schema
source: /src/
paths:
  uploads: uploads
  static: ''
collections_config:
  posts:
    path: content/posts
    url: '/blog/[slug]'
    output: true
    _enabled_editors:
      - content
      - data