_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  posts:
    path:
    glob: []
    name:
    singular_name:
    icon: notes
    url: http://localhost:3000/posts
    disable_url: false
    include_developer_files:
    documentation:
    description:
    preview:
    sort:
    sort_options:
    _editables:
      block:
        allow_custom_markup: true
        remove_custom_markup: false
        blockquote: true
        bold: true
        bulletedlist: true
        center:
        code: true
        copyformatting: true
        embed: true
        expandable: true
        format:
        height:
        horizontalrule:
        image: true
        image_size_attributes: true
        indent:
        italic: true
        justify:
        left:
        link: true
        mime_type:
        numberedlist: true
        outdent: true
        paths:
        redo: true
        removeformat: true
        resize_style: cover
        right:
        snippet:
        strike:
        styles:
        subscript: true
        superscript: true
        table: true
        underline: true
        undo: true
        width:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Asia/Calcutta
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
