_schema: _schema
source: /src/
paths:
  uploads: uploads
  static: ''
collections_config:
  posts:
    path: content/posts
    url: '/blog/[slug]'
    output: true
    _enabled_editors:
      - content
      - data
  # pages:
    path: /src/pages
    glob: ["**/*.md"]
    name: Pages
    singular_name: Page
    icon: notes
    url: /:title/
    disable_url: false
    include_developer_files: false
    documentation:
    description: 'Collection of pages'
    preview:
    sort: date
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
      navbar:
        path: src/schemas/navbar.schema.js
      footer:
        path: src/schemas/footer.schema.js
      hero:
        path: src/schemas/hero.schema.js
      about:
        path: src/schemas/about.schema.js
      services:
        path: src/schemas/services.schema.js
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
# timezone: Asia/Calcutta
# markdown:
#   engine: commonmark
#   options:
#     xhtml: false
#     breaks: false
#     linkify: false
#     typographer: false
#     spaced_lists: false
#     sentence_per_line: false
#     gfm: false
#     code_block_fences: '```'
#     escape_snippets_in_code_blocks: false
#     treat_indentation_as_code: false
#     table: false
#     strikethrough: false
#     subscript: false
#     superscript: false
#     heading_ids: false
#     attributes: false
