collections_config:
  webpages:
    path: content/pages
    url: '/[slug]'
    output: true
    name: Pages
    icon: wysiwyg
    _enabled_editors:
      - visual
      - data
  posts:
    path: content/posts
    url: '/blog/[slug]'
    output: true
    _enabled_editors:
      - content
      - data